"""
Knowledge base for CropDoc AI.

Each crop maps to a set of possible diagnoses. Every diagnosis entry carries
the visual signature (used by the analyzer in inference.py to score a match)
plus the agronomy content shown to the user: symptoms, cause, treatment, and
prevention steps.
"""

DISEASE_DB = {
    "tomato": {
        "label": "Tomato",
        "conditions": [
            {
                "id": "tomato_healthy",
                "name": "Healthy",
                "severity": "none",
                "signature": {"green": "high", "brown": "low", "yellow": "low", "spots": "low"},
                "summary": "Leaf tissue shows even chlorophyll distribution with no necrotic or chlorotic lesions.",
                "symptoms": ["Uniform deep-green color", "No lesions or wilting", "Firm leaf structure"],
                "cause": "N/A",
                "treatment": ["No treatment needed", "Continue routine monitoring"],
                "prevention": ["Maintain consistent watering", "Rotate crops yearly", "Scout weekly for early symptoms"],
            },
            {
                "id": "tomato_early_blight",
                "name": "Early Blight",
                "severity": "moderate",
                "signature": {"green": "medium", "brown": "medium", "yellow": "medium", "spots": "high"},
                "summary": "Fungal disease (Alternaria solani) causing concentric 'target-ring' brown spots, usually starting on lower, older leaves.",
                "symptoms": ["Dark brown spots with concentric rings", "Yellow halo around lesions", "Lower leaves affected first"],
                "cause": "Fungus Alternaria solani, favored by warm, humid conditions and leaf wetness.",
                "treatment": ["Remove and destroy infected leaves", "Apply chlorothalonil or copper-based fungicide", "Improve airflow via pruning"],
                "prevention": ["Mulch to prevent soil splash", "Avoid overhead irrigation", "Rotate with non-solanaceous crops"],
            },
            {
                "id": "tomato_late_blight",
                "name": "Late Blight",
                "severity": "severe",
                "signature": {"green": "low", "brown": "high", "yellow": "low", "spots": "high"},
                "summary": "Aggressive water-mold disease (Phytophthora infestans) that can destroy a field within days in cool, wet weather.",
                "symptoms": ["Large irregular water-soaked patches", "Pale green to brown/black blotches", "White fuzzy mold on leaf underside in humid conditions"],
                "cause": "Oomycete Phytophthora infestans, spreads rapidly in cool wet weather.",
                "treatment": ["Apply systemic fungicide (e.g. mefenoxam) immediately", "Remove and bag infected plants", "Avoid working in wet fields to prevent spread"],
                "prevention": ["Use certified disease-free seed/transplants", "Ensure good drainage and spacing", "Monitor regional blight forecasts"],
            },
            {
                "id": "tomato_leaf_mold",
                "name": "Leaf Mold",
                "severity": "moderate",
                "signature": {"green": "medium", "brown": "low", "yellow": "high", "spots": "medium"},
                "summary": "Fungal disease (Passalora fulva) common in greenhouses, showing pale yellow patches on top with olive-green mold beneath.",
                "symptoms": ["Pale yellow spots on upper leaf surface", "Olive-green to grayish mold on underside", "Leaf curling and drop in severe cases"],
                "cause": "Fungus Passalora fulva, thrives in high humidity (>85%) with poor ventilation.",
                "treatment": ["Increase ventilation and reduce humidity", "Apply fungicide labeled for leaf mold", "Remove heavily infected foliage"],
                "prevention": ["Space plants for airflow", "Avoid wetting foliage when watering", "Use resistant varieties"],
            },
        ],
    },
    "potato": {
        "label": "Potato",
        "conditions": [
            {
                "id": "potato_healthy",
                "name": "Healthy",
                "severity": "none",
                "signature": {"green": "high", "brown": "low", "yellow": "low", "spots": "low"},
                "summary": "No visible lesions; leaf color and structure are typical of a healthy potato plant.",
                "symptoms": ["Even green coloration", "No spotting or curling"],
                "cause": "N/A",
                "treatment": ["No treatment needed"],
                "prevention": ["Hill soil around stems", "Monitor for early pest/disease signs"],
            },
            {
                "id": "potato_early_blight",
                "name": "Early Blight",
                "severity": "moderate",
                "signature": {"green": "medium", "brown": "medium", "yellow": "medium", "spots": "high"},
                "summary": "Alternaria solani produces dark, target-spot lesions primarily on older foliage.",
                "symptoms": ["Concentric brown rings ('bullseye' lesions)", "Yellowing around spots", "Lower canopy affected first"],
                "cause": "Fungus Alternaria solani, favored by warm temperatures and plant stress.",
                "treatment": ["Apply protectant fungicide (chlorothalonil/mancozeb)", "Remove infected debris post-harvest"],
                "prevention": ["Maintain balanced fertility (avoid N stress)", "3-4 year crop rotation", "Irrigate at soil level"],
            },
            {
                "id": "potato_late_blight",
                "name": "Late Blight",
                "severity": "severe",
                "signature": {"green": "low", "brown": "high", "yellow": "low", "spots": "high"},
                "summary": "The pathogen behind the Irish Potato Famine; causes rapid, water-soaked lesions that turn brown-black.",
                "symptoms": ["Water-soaked pale-green to brown lesions", "White mold ring on leaf underside", "Rapid tissue collapse and rot smell"],
                "cause": "Oomycete Phytophthora infestans, spreads explosively in cool wet weather.",
                "treatment": ["Apply systemic fungicide immediately", "Destroy infected plants/tubers", "Harvest early if outbreak is severe"],
                "prevention": ["Plant certified seed potatoes", "Hill soil to protect tubers", "Avoid irrigation during outbreaks"],
            },
        ],
    },
    "maize": {
        "label": "Corn / Maize",
        "conditions": [
            {
                "id": "maize_healthy",
                "name": "Healthy",
                "severity": "none",
                "signature": {"green": "high", "brown": "low", "yellow": "low", "spots": "low"},
                "summary": "Leaf blade shows normal green striping with no lesions or rust pustules.",
                "symptoms": ["Uniform green color", "No pustules or streaking"],
                "cause": "N/A",
                "treatment": ["No treatment needed"],
                "prevention": ["Continue balanced nitrogen program", "Scout regularly"],
            },
            {
                "id": "maize_rust",
                "name": "Common Rust",
                "severity": "moderate",
                "signature": {"green": "medium", "brown": "high", "yellow": "low", "spots": "high"},
                "summary": "Puccinia sorghi produces small, cinnamon-brown raised pustules scattered on both leaf surfaces.",
                "symptoms": ["Small oval reddish-brown pustules", "Pustules rupture releasing powdery spores", "Pustules on both leaf sides"],
                "cause": "Fungus Puccinia sorghi, spread by windborne spores in cool humid weather.",
                "treatment": ["Apply foliar fungicide if severe before tasseling", "Select rust-resistant hybrids next season"],
                "prevention": ["Plant resistant hybrids", "Avoid dense over-fertilized stands", "Monitor during humid periods"],
            },
            {
                "id": "maize_gray_leaf_spot",
                "name": "Gray Leaf Spot",
                "severity": "severe",
                "signature": {"green": "low", "brown": "medium", "yellow": "low", "spots": "high"},
                "summary": "Cercospora zeae-maydis causes narrow, rectangular gray-brown lesions that run parallel to leaf veins.",
                "symptoms": ["Narrow rectangular tan-to-gray lesions", "Lesions bound by leaf veins", "Lesions coalesce, blighting entire leaves"],
                "cause": "Fungus Cercospora zeae-maydis, favored by warm humid weather and continuous corn planting.",
                "treatment": ["Apply strobilurin/triazole fungicide at early symptom onset", "Improve field residue management"],
                "prevention": ["Rotate away from corn 1-2 years", "Tillage to bury infected residue", "Use resistant hybrids"],
            },
        ],
    },
    "apple": {
        "label": "Apple",
        "conditions": [
            {
                "id": "apple_healthy",
                "name": "Healthy",
                "severity": "none",
                "signature": {"green": "high", "brown": "low", "yellow": "low", "spots": "low"},
                "summary": "Leaf surface is smooth and evenly green with no scab lesions or rust spots.",
                "symptoms": ["Even green color", "No velvety or rust-colored lesions"],
                "cause": "N/A",
                "treatment": ["No treatment needed"],
                "prevention": ["Prune for airflow", "Continue seasonal monitoring"],
            },
            {
                "id": "apple_scab",
                "name": "Apple Scab",
                "severity": "moderate",
                "signature": {"green": "medium", "brown": "medium", "yellow": "low", "spots": "high"},
                "summary": "Venturia inaequalis produces olive-green to brown velvety spots, later causing leaf distortion and drop.",
                "symptoms": ["Olive-green velvety spots", "Spots darken and become scab-like", "Premature leaf drop"],
                "cause": "Fungus Venturia inaequalis, overwinters in fallen leaves and spreads in wet spring weather.",
                "treatment": ["Apply fungicide (captan/myclobutanil) at green tip stage", "Rake and destroy fallen leaves"],
                "prevention": ["Plant scab-resistant cultivars", "Improve canopy airflow via pruning", "Remove leaf litter each fall"],
            },
            {
                "id": "apple_rust",
                "name": "Cedar Apple Rust",
                "severity": "moderate",
                "signature": {"green": "medium", "brown": "low", "yellow": "high", "spots": "high"},
                "summary": "Gymnosporangium juniperi-virginianae produces bright orange-yellow lesions; requires a nearby juniper/cedar host.",
                "symptoms": ["Bright yellow-orange spots on upper leaf", "Small black dots within spots", "Tube-like structures on underside later season"],
                "cause": "Fungus requiring alternating hosts between apple and juniper/cedar trees.",
                "treatment": ["Apply protectant fungicide from pink bud stage", "Remove nearby juniper hosts if feasible"],
                "prevention": ["Plant rust-resistant varieties", "Keep distance from juniper/cedar trees"],
            },
        ],
    },
    "grape": {
        "label": "Grape",
        "conditions": [
            {
                "id": "grape_healthy",
                "name": "Healthy",
                "severity": "none",
                "signature": {"green": "high", "brown": "low", "yellow": "low", "spots": "low"},
                "summary": "Leaf shows normal green color with no fungal lesions or discoloration.",
                "symptoms": ["Even green color", "No lesions or leaf curl"],
                "cause": "N/A",
                "treatment": ["No treatment needed"],
                "prevention": ["Maintain canopy management", "Routine scouting"],
            },
            {
                "id": "grape_black_rot",
                "name": "Black Rot",
                "severity": "severe",
                "signature": {"green": "low", "brown": "high", "yellow": "low", "spots": "high"},
                "summary": "Guignardia bidwellii causes reddish-brown circular leaf spots with dark pycnidia specks, and can rot fruit entirely.",
                "symptoms": ["Reddish-brown circular lesions", "Tiny black fruiting bodies inside spots", "Fruit shrivels into black 'mummies'"],
                "cause": "Fungus Guignardia bidwellii, favored by warm wet weather from bloom through veraison.",
                "treatment": ["Apply fungicide program from bud break through veraison", "Remove mummified fruit and infected canes"],
                "prevention": ["Prune for canopy airflow", "Remove overwintering mummies and infected wood", "Use resistant rootstock where available"],
            },
            {
                "id": "grape_esca",
                "name": "Esca (Black Measles)",
                "severity": "severe",
                "signature": {"green": "medium", "brown": "medium", "yellow": "high", "spots": "medium"},
                "summary": "A complex trunk-disease showing interveinal 'tiger-stripe' yellowing and browning between leaf veins.",
                "symptoms": ["Interveinal yellow and brown striping", "Tiger-stripe pattern between veins", "Sudden shoot collapse in severe (apoplectic) form"],
                "cause": "Complex of wood-rotting fungi entering through pruning wounds.",
                "treatment": ["No curative fungicide; remove and destroy affected wood", "Retrain trunks from healthy suckers"],
                "prevention": ["Prune during dry weather", "Protect large pruning wounds", "Avoid pruning stressed vines in wet conditions"],
            },
        ],
    },
    "wheat": {
        "label": "Wheat",
        "conditions": [
            {
                "id": "wheat_healthy",
                "name": "Healthy",
                "severity": "none",
                "signature": {"green": "high", "brown": "low", "yellow": "low", "spots": "low"},
                "summary": "Leaf blade is uniformly green with no pustules, lesions, or streaking.",
                "symptoms": ["Even green color", "No pustules or lesions"],
                "cause": "N/A",
                "treatment": ["No treatment needed"],
                "prevention": ["Continue balanced fertility program", "Scout at key growth stages"],
            },
            {
                "id": "wheat_leaf_rust",
                "name": "Leaf Rust",
                "severity": "moderate",
                "signature": {"green": "medium", "brown": "high", "yellow": "low", "spots": "high"},
                "summary": "Puccinia triticina causes small round orange-brown pustules scattered over the upper leaf surface.",
                "symptoms": ["Small round orange-brown pustules", "Pustules mainly on upper leaf surface", "Yellowing around heavily infected areas"],
                "cause": "Fungus Puccinia triticina, spread by windborne urediniospores in mild humid weather.",
                "treatment": ["Apply triazole/strobilurin fungicide if above threshold", "Plant resistant varieties next season"],
                "prevention": ["Use resistant cultivars", "Avoid excessive nitrogen", "Monitor regional rust reports"],
            },
            {
                "id": "wheat_septoria",
                "name": "Septoria Leaf Blotch",
                "severity": "moderate",
                "signature": {"green": "low", "brown": "medium", "yellow": "medium", "spots": "high"},
                "summary": "Zymoseptoria tritici produces irregular tan-brown blotches speckled with tiny black fruiting bodies.",
                "symptoms": ["Irregular tan-brown lesions", "Tiny black pycnidia specks within lesions", "Lower leaves infected first, moving up canopy"],
                "cause": "Fungus Zymoseptoria tritici, favored by cool wet weather and splash-dispersed spores.",
                "treatment": ["Apply fungicide at flag-leaf emergence if disease pressure is high", "Remove volunteer wheat and residue"],
                "prevention": ["Rotate crops", "Use resistant varieties", "Bury or remove infected stubble"],
            },
        ],
    },
}

CROP_CHOICES = [(key, val["label"]) for key, val in DISEASE_DB.items()]
